import React, {useEffect} from 'react';
import Aos from 'aos';
import {Media, Container } from 'react-bootstrap';
import styled from 'styled-components';


const Styles = styled.div`

.shake-horizontal {
	-webkit-animation: shake-horizontal 0.8s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
	        animation: shake-horizontal 0.8s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-2-7 5:57:29
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation shake-horizontal
 * ----------------------------------------
 */
@-webkit-keyframes shake-horizontal {
  0%,
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
  }
  10%,
  30%,
  50%,
  70% {
    -webkit-transform: translateX(-10px);
            transform: translateX(-10px);
  }
  20%,
  40%,
  60% {
    -webkit-transform: translateX(10px);
            transform: translateX(10px);
  }
  80% {
    -webkit-transform: translateX(8px);
            transform: translateX(8px);
  }
  90% {
    -webkit-transform: translateX(-8px);
            transform: translateX(-8px);
  }
}
@keyframes shake-horizontal {
  0%,
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
  }
  10%,
  30%,
  50%,
  70% {
    -webkit-transform: translateX(-10px);
            transform: translateX(-10px);
  }
  20%,
  40%,
  60% {
    -webkit-transform: translateX(10px);
            transform: translateX(10px);
  }
  80% {
    -webkit-transform: translateX(8px);
            transform: translateX(8px);
  }
  90% {
    -webkit-transform: translateX(-8px);
            transform: translateX(-8px);
  }
}


    .media img{
        height: 300px;
        width: 400px;
        margin-bottom: 80px;
        background-color: rgb(240, 229, 229);
        &:hover{

        }
    }
    @media screen and (max-width: 880px){
        .media img{
            width: 50%;
            height: 50%;
            display: flex;
        }
    }



`;




function AboutMedia() {
    useEffect(()  => {
        
        Aos.init ({ duration: 2000 });
      }, []);

    return (
        <Styles>
            <Container>
            <h2 className='shake-horizontal mb-5' data-aos='slide-down'>About GmeeJay Media</h2>
        <div className='row'>
              <div className='col-10'>
        <Media className='media'>
            <img
                className="mr-3 download"
                src="./images/wedding.jpg"
                alt="pics"
                title='JIMMY JOHNSON'
            />
            <Media.Body>
                
                <p>
                "The beauty of marriage is not always seen from the very beginning—but rather as love grows and develops over time....."<cite>Fawn Weaver</cite>
                </p>
            </Media.Body>
        </Media>
        </div>
        </div>
        <hr />
        </Container>
        </Styles>
        
    )
}

export default AboutMedia;
